database:
  # NOTE: By design, this setting prevents the PGDATABASE environment variable
  # from affecting test runs, so that we don't accidentally affect the
  # production database during testing. If you're not concerned about that and
  # would like to have environment variable overrides, you could instead use
  # something like:
  #
  #   database: "_env:PGDATABASE:yesod-crud_test"
  database: "postgres-test"
  host: "_env:YESOD_PGHOST:db-test"
  user: "_env:YESOD_PGUSER:postgres"
  password: "_env:YESOD_PGPASS:asdf"

auth-dummy-login: true
