version: '3.7'
services:
  haskell:
    build: .
    volumes:
    - .:/mnt
    ports:
    - 8000

  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_PASSWORD: "asdf"

  db-test:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: "postgres-test"
      POSTGRES_PASSWORD: "asdf"
